url: "https://wonderchatai.github.io"
baseurl: "/jekyll-bootstrap"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji
  - kramdown-parser-gfm
  - rouge
minimal_mistakes_skin: "default"
head_scripts:
  - /assets/css/custom.css
